model:
  type: gcn
  n_hidden: 128
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: F.relu # [relu, elu, gelu, leakyrelu, identity]
  dropout: 0.5
  input_dropout: 0
  norm: ~
  input_layer: false
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions

gsl:
  n_hidden: 128
  n_embed: 32
  n_layers: 2
  n_linear: 1 # layers of linear per gcn layer
  act: 'lambda x: x' # [relu, elu, gelu, leakyrelu, identity]
  dropout: 0
  input_dropout: 0
  norm: ~
  input_layer: false
  output_layer: false
  spmm_type: 0 # specilized for sparse mltiply [0,1], expected to remove in future versions
  gae: true
  alpha: 0.05
  temperature: 1.9
  remove_ratio: 0.55
  add_ratio: 0.7

dataset:
  feat_norm: true
  cora_split: false # for cora,citeseer and pubmed
  sparse: true

training:
  lr: 1e-2
  n_epochs: 200
  weight_decay: 5e-4
  warmup: 10
  patience: 100
  pretrain_ep: 5
  pretrain_nc: 300
  beta: 0.8
  gamma: 0.4
  criterion: ~
  use_pre_model: true
  seed: 3

# analysis
analysis:
  flag: false
  project: gsl
  save_graph: false
  save_graph_path: results/graph